### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by MilkiFauzan**
<h1 align="center">Hi 👋, I'm Milki Fauzan Tsany</h1>
<h3 align="center">A passionate fullstack developer from Indonesia</h3>

- 🌱 I’m currently learning **Javascript**

<h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://dev.to/milkifauzan" target="blank">milkifauzan</a>
<a href="https://linkedin.com/in/milkifauzantsany" target="blank">milkifauzantsany</a>
<a href="https://instagram.com/milkyfauzan" target="blank">milkyfauzan</a>
</p>

<h3 align="left">Languages and Tools:</h3>
<p align="left"> <a href="https://www.blender.org/" target="_blank" rel="noreferrer"> blender </a> <a href="https://getbootstrap.com" target="_blank" rel="noreferrer"> bootstrap </a> <a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer"> css3 </a> <a href="https://www.figma.com/" target="_blank" rel="noreferrer"> figma </a> <a href="https://git-scm.com/" target="_blank" rel="noreferrer"> git </a> <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer"> html5 </a> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank" rel="noreferrer"> javascript </a> <a href="https://nodejs.org" target="_blank" rel="noreferrer"> nodejs </a> </p>

### CODE REVIEW

**Comment by xxidbr9** [comment]
@MilkiFauzan tolong ikuti yang lain, buat file baru dan hanya tambah link di file README.md

**Comment by MilkiFauzan** [comment]
sudah diupdate mas

**Comment by xxidbr9** [comment]
@MilkiFauzan buat pull request lagi mas

**Comment by MilkiFauzan** [comment]
lupa ganti branch kayanya

**Pull request closed without merging**
